#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton --config ~/.config/compton/compton.conf &
wmname LG3D &
feh --bg-fill ~/.config/bspwm/scripts/wallpaper.jpg &

terminator -e ~/.config/bspwm/.mensaje

~/.config/polybar/launch.sh --hack &
bspc config monitor pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Firefox desktop= '^2' follow=on
bspc rule -a qterminal desktop='^10' state=floating
bspc rule -a Thunar desktop='^3' state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

